name: Giraffe Workflow
on: [workflow_dispatch, push]
jobs:
  Install-and-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Install dependencies
        run: npm ci
      - name: Test code
        run: npm run test-workflow
      - name: Finish workflow
        run: echo "Done with workflow"